### ISSUE TITLE
Add more time periods + custom reason to ban disconnected player

### ISSUE THREAD

**Issue by Richard-CRT** [meev/SourceCode#29]
Only options for time period are:
1 hour,
4 hours,
1 day,
1 week
and other options in both directions of that. I'm thinking 10 hours should be on there so it fits with the official rules. Also, could you add either "Calladmin Abuse" or a custom reason option to the reasons of Ban disconnected player.

**Comment by meev** [comment]
the menu should now have appropiate menus both in ban disconnected and the normal one, I didnt make the custom one on ban disconnected though.
