### ISSUE TITLE
Top 30 ranked players on the servers

### ISSUE THREAD

**Issue by originall** [meev/SourceCode#49]
Shows the current top 30 ranked players, according to !rank, on Deathrun and Bhop - also the other servers if they have !rank implemented 

(If you get what I mean)

**Comment by Bosturk** [comment]
+rep, would love to see this implemented (possibly on webtimes?)

**Comment by Swanne** [comment]
I'd Like To See Something Like This Too, Good Idea Nerd ;)

**Comment by meev** [comment]
This is already planned, but I am going to leave the issue here anyway thanks for that

**Comment by meev** [comment]
Closing this since the title is consfusing vs what I am making for this
