### ISSUE TITLE
Admins on server #1 can remove mutes/gags (to themselves) issued on server #2

### ISSUE THREAD

**Issue by Richard-CRT** [meev/SourceCode#50]
Title - example being if DR Admin 1 was muted in MG by MG Admin 1, DR Admin 1 can go to DR and remove the mute upon themself

**Comment by Bosturk** [comment]
Not sure if this is a github issue, I think the issue would rather be admins having to mute other admins in the first place. (?)

**Comment by Richard-CRT** [comment]
Going for the systematic point of view here really as opposed to the "why would it happen" view point
