### ISSUE TITLE
[Suggestion] Show a C or I for Complete or Incomplete map when voting for a map

### ISSUE THREAD

**Issue by Bosturk** [meev/SourceCode#57]
When voting for the next map this would be a nice bonus to see which maps you have and have not completed. This will allow for easier rank grinding.

**Comment by originall** [comment]
Or even cooler, shows your time next to the map name

**Comment by meev** [comment]
Would be a neat feature, but it requires a lot of integration with the map chooser plugin so I made a !mapsdone which solves the problem pretty well
