### ISSUE TITLE
[Forum] Switch save draft and Submit + Quick reply

### ISSUE THREAD

**Issue by Bosturk** [meev/SourceCode#69]
I don't know if it's just me but as you read from left to right, the most logical choice is presented first. In this case being Submit. I find myself pressing save draft instead of Submit all the time. 

This also seems to be more in harmony with other forums as is seen here http://i.imgur.com/coZz866.png
and here http://i.imgur.com/aeaqrHB.png
You know actually just myBB in general.

To this I would like to add quick replying. This makes it easier to scroll up and see exactly what you were replying to again and saves you some clicks. I don't know how hard this is to integrate and this is obviously not an important feature.

**Comment by Richard-CRT** [comment]
Can you clarify the quick replying thing?
