### ISSUE TITLE
VIP isn't loaded until !profile is used

### ISSUE THREAD

**Issue by Bosturk** [meev/SourceCode#80]
I get VIP on DR because I'm admin, I don't have normal VIP.
I have a color set but it is not applied as I join the server. 
If I type !profile and then exit that, my color is applied and I get a 4.5x bonus instead of 3.5x.

**Comment by Bosturk** [comment]
Hi mev,

This was fixed, I don't know if you intentionally did that but this can be closed now.

**Comment by meev** [comment]
This was probably something regarding me reloading the store randomly
