### ISSUE TITLE
Map voting hides some of the options after you've voted

### ISSUE THREAD

**Issue by addonem** [meev/SourceCode#83]
![20160511201045_1](https://cloud.githubusercontent.com/assets/17725374/15191360/ac22fc4e-17b4-11e6-84c6-dbfeafd4e2c8.jpg)
![20160511201041_1](https://cloud.githubusercontent.com/assets/17725374/15191362/ac372dd6-17b4-11e6-961f-595dffc2ac04.jpg)
As shown, mg_warmcup disappears in the list after I've voted on a map

**Comment by addonem** [comment]
As of the latest 3 votes, it's always been the first option that disappears.

**Comment by Richard-CRT** [comment]
Can confirm, happens on the other servers too

**Comment by meev** [comment]
Working on new map manager anyway so ill close this
