### ISSUE TITLE
!hide stating the wrong setting

### ISSUE THREAD

**Issue by addonem** [meev/SourceCode#88]
![20160607192013_1](https://cloud.githubusercontent.com/assets/17725374/15867750/f4f8862e-2ce4-11e6-973b-f00de51e346c.jpg)
![20160607192005_1](https://cloud.githubusercontent.com/assets/17725374/15867751/f4fa8a3c-2ce4-11e6-8f4c-6d97dae0f2df.jpg)
Might have something to do with the cookies saved from MG, I had hide **activated** on MG when connecting to bhop and I could see everyone.

**Comment by meev** [comment]
Fixed in most recent timer version
